/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encryption.ui;

import encryption.Configuration;
import encryption.Project;
import encryption.algorithm.Algorithm;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author marko
 */
public class ProjectForm extends javax.swing.JPanel {

    /**
     * Creates new form ProjectForm
     */
    public ProjectForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        inputFolderChooser = new javax.swing.JFileChooser();
        outputFolderChooser = new javax.swing.JFileChooser();
        algorithmConfigurationChooser = new javax.swing.JFileChooser();
        project = new encryption.Project();
        inputFolderTextField = new javax.swing.JTextField();
        outputFolderTextField = new javax.swing.JTextField();
        chooseInputFolderButton = new javax.swing.JButton();
        chooseOutputFolderButton = new javax.swing.JButton();
        inputFolderLabel = new javax.swing.JLabel();
        outputFolderLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        algorithmLabel = new javax.swing.JLabel();
        algorithmComboBox = new javax.swing.JComboBox();
        chooseAlgorithmConfigurationButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        filesSplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        inputFilesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        rightPanel = new javax.swing.JPanel();
        outputFilesLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        inputFolderChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project, org.jdesktop.beansbinding.ELProperty.create("${inputFolder}"), inputFolderChooser, org.jdesktop.beansbinding.BeanProperty.create("selectedFile"));
        bindingGroup.addBinding(binding);

        outputFolderChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project, org.jdesktop.beansbinding.ELProperty.create("${outputFolder}"), outputFolderChooser, org.jdesktop.beansbinding.BeanProperty.create("selectedFile"));
        bindingGroup.addBinding(binding);

        inputFolderTextField.setEditable(false);
        inputFolderTextField.setDoubleBuffered(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project, org.jdesktop.beansbinding.ELProperty.create("${inputFolder.absolutePath}"), inputFolderTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        outputFolderTextField.setEditable(false);
        outputFolderTextField.setDoubleBuffered(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project, org.jdesktop.beansbinding.ELProperty.create("${outputFolder.absolutePath}"), outputFolderTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        chooseInputFolderButton.setText("Browse");
        chooseInputFolderButton.setDoubleBuffered(true);
        chooseInputFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseInputFolderButtonActionPerformed(evt);
            }
        });

        chooseOutputFolderButton.setText("Browse");
        chooseOutputFolderButton.setDoubleBuffered(true);
        chooseOutputFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseOutputFolderButtonActionPerformed(evt);
            }
        });

        inputFolderLabel.setText("Input Folder");
        inputFolderLabel.setDoubleBuffered(true);

        outputFolderLabel.setText("Output Folder");
        outputFolderLabel.setDoubleBuffered(true);

        jSeparator1.setDoubleBuffered(true);

        algorithmLabel.setText("Encryption Algorithm");
        algorithmLabel.setDoubleBuffered(true);

        algorithmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        algorithmComboBox.setDoubleBuffered(true);

        chooseAlgorithmConfigurationButton.setText("Browse Configuration");
        chooseAlgorithmConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAlgorithmConfigurationButtonActionPerformed(evt);
            }
        });

        jSeparator2.setDoubleBuffered(true);

        filesSplitPane.setDividerLocation(240);
        filesSplitPane.setDoubleBuffered(true);

        inputFilesLabel.setText("Input Files");
        inputFilesLabel.setDoubleBuffered(true);

        jScrollPane3.setDoubleBuffered(true);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setDoubleBuffered(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${inputFiles}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project, eLProperty, jList1);
        bindingGroup.addBinding(jListBinding);

        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(inputFilesLabel)
                        .addGap(0, 146, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputFilesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        filesSplitPane.setLeftComponent(leftPanel);

        outputFilesLabel.setText("Output Files");
        outputFilesLabel.setDoubleBuffered(true);

        jScrollPane4.setDoubleBuffered(true);

        jList2.setDoubleBuffered(true);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${outputFiles}");
        jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project, eLProperty, jList2);
        bindingGroup.addBinding(jListBinding);

        jScrollPane4.setViewportView(jList2);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(outputFilesLabel)
                        .addGap(0, 321, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputFilesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        filesSplitPane.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filesSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputFolderLabel)
                            .addComponent(inputFolderLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputFolderTextField)
                            .addComponent(inputFolderTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseInputFolderButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseOutputFolderButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(algorithmLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(algorithmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chooseAlgorithmConfigurationButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseInputFolderButton)
                    .addComponent(inputFolderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseOutputFolderButton)
                    .addComponent(outputFolderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(algorithmLabel)
                    .addComponent(algorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseAlgorithmConfigurationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filesSplitPane)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseInputFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseInputFolderButtonActionPerformed
        int ret = inputFolderChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION)
            project.setInputFolder(inputFolderChooser.getSelectedFile());
        
    }//GEN-LAST:event_chooseInputFolderButtonActionPerformed

    private void chooseOutputFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseOutputFolderButtonActionPerformed
        int ret = outputFolderChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION)
            project.setOutputFolder(outputFolderChooser.getSelectedFile());
    }//GEN-LAST:event_chooseOutputFolderButtonActionPerformed

    private void chooseAlgorithmConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseAlgorithmConfigurationButtonActionPerformed
        int ret = algorithmConfigurationChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            try {
                Configuration configuration = new Configuration(algorithmConfigurationChooser.getSelectedFile());
                project.setAlgorithm(new Algorithm(configuration));
                project.work();
            } catch (Exception ex) {
                Logger.getLogger(ProjectForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_chooseAlgorithmConfigurationButtonActionPerformed

    
    
    public Project getProject() {
        return project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algorithmComboBox;
    private javax.swing.JFileChooser algorithmConfigurationChooser;
    private javax.swing.JLabel algorithmLabel;
    private javax.swing.JButton chooseAlgorithmConfigurationButton;
    private javax.swing.JButton chooseInputFolderButton;
    private javax.swing.JButton chooseOutputFolderButton;
    private javax.swing.JSplitPane filesSplitPane;
    private javax.swing.JLabel inputFilesLabel;
    private javax.swing.JFileChooser inputFolderChooser;
    private javax.swing.JLabel inputFolderLabel;
    private javax.swing.JTextField inputFolderTextField;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel outputFilesLabel;
    private javax.swing.JFileChooser outputFolderChooser;
    private javax.swing.JLabel outputFolderLabel;
    private javax.swing.JTextField outputFolderTextField;
    private encryption.Project project;
    private javax.swing.JPanel rightPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
